#############################################################################
# Makefile for building: notifier
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Oct 31 13:54:08 2016
# Project:  notifier.pro
# Template: subdirs
# Command: d:\Qt\4.8.6\bin\qmake.exe -spec ..\..\..\..\Qt\4.8.6\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile notifier.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = d:\Qt\4.8.6\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-notifier \
		sub-daemon

notifier\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) notifier\ $(MKDIR) notifier\ 
	cd notifier\ && $(QMAKE) d:\Libraries\Documents\GitHub\notifier\notifier\notifier.pro -spec d:\Qt\4.8.6\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-notifier-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) notifier\ $(MKDIR) notifier\ 
	cd notifier\ && $(QMAKE) d:\Libraries\Documents\GitHub\notifier\notifier\notifier.pro -spec d:\Qt\4.8.6\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-notifier: notifier\$(MAKEFILE) FORCE
	cd notifier\ && $(MAKE) -f $(MAKEFILE)
sub-notifier-make_default: notifier\$(MAKEFILE) FORCE
	cd notifier\ && $(MAKE) -f $(MAKEFILE) 
sub-notifier-make_first: notifier\$(MAKEFILE) FORCE
	cd notifier\ && $(MAKE) -f $(MAKEFILE) first
sub-notifier-all: notifier\$(MAKEFILE) FORCE
	cd notifier\ && $(MAKE) -f $(MAKEFILE) all
sub-notifier-clean: notifier\$(MAKEFILE) FORCE
	cd notifier\ && $(MAKE) -f $(MAKEFILE) clean
sub-notifier-distclean: notifier\$(MAKEFILE) FORCE
	cd notifier\ && $(MAKE) -f $(MAKEFILE) distclean
sub-notifier-install_subtargets: notifier\$(MAKEFILE) FORCE
	cd notifier\ && $(MAKE) -f $(MAKEFILE) install
sub-notifier-uninstall_subtargets: notifier\$(MAKEFILE) FORCE
	cd notifier\ && $(MAKE) -f $(MAKEFILE) uninstall
daemon\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) daemon\ $(MKDIR) daemon\ 
	cd daemon\ && $(QMAKE) d:\Libraries\Documents\GitHub\notifier\daemon\daemon.pro -spec d:\Qt\4.8.6\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-daemon-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) daemon\ $(MKDIR) daemon\ 
	cd daemon\ && $(QMAKE) d:\Libraries\Documents\GitHub\notifier\daemon\daemon.pro -spec d:\Qt\4.8.6\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-daemon: daemon\$(MAKEFILE) FORCE
	cd daemon\ && $(MAKE) -f $(MAKEFILE)
sub-daemon-make_default: daemon\$(MAKEFILE) FORCE
	cd daemon\ && $(MAKE) -f $(MAKEFILE) 
sub-daemon-make_first: daemon\$(MAKEFILE) FORCE
	cd daemon\ && $(MAKE) -f $(MAKEFILE) first
sub-daemon-all: daemon\$(MAKEFILE) FORCE
	cd daemon\ && $(MAKE) -f $(MAKEFILE) all
sub-daemon-clean: daemon\$(MAKEFILE) FORCE
	cd daemon\ && $(MAKE) -f $(MAKEFILE) clean
sub-daemon-distclean: daemon\$(MAKEFILE) FORCE
	cd daemon\ && $(MAKE) -f $(MAKEFILE) distclean
sub-daemon-install_subtargets: daemon\$(MAKEFILE) FORCE
	cd daemon\ && $(MAKE) -f $(MAKEFILE) install
sub-daemon-uninstall_subtargets: daemon\$(MAKEFILE) FORCE
	cd daemon\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: notifier.pro  ../../../../Qt/4.8.6/mkspecs/win32-g++/qmake.conf ../../../../Qt/4.8.6/mkspecs/features/device_config.prf \
		../../../../Qt/4.8.6/mkspecs/qconfig.pri \
		../../../../Qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		../../../../Qt/4.8.6/mkspecs/features/qt_functions.prf \
		../../../../Qt/4.8.6/mkspecs/features/qt_config.prf \
		../../../../Qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/4.8.6/mkspecs/features/default_pre.prf \
		../../../../Qt/4.8.6/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/4.8.6/mkspecs/features/debug.prf \
		../../../../Qt/4.8.6/mkspecs/features/debug_and_release.prf \
		../../../../Qt/4.8.6/mkspecs/features/default_post.prf \
		../../../../Qt/4.8.6/mkspecs/features/win32/default_post.prf \
		../../../../Qt/4.8.6/mkspecs/features/declarative_debug.prf \
		../../../../Qt/4.8.6/mkspecs/features/win32/rtti.prf \
		../../../../Qt/4.8.6/mkspecs/features/win32/exceptions.prf \
		../../../../Qt/4.8.6/mkspecs/features/win32/stl.prf \
		../../../../Qt/4.8.6/mkspecs/features/shared.prf \
		../../../../Qt/4.8.6/mkspecs/features/warn_on.prf \
		../../../../Qt/4.8.6/mkspecs/features/qt.prf \
		../../../../Qt/4.8.6/mkspecs/features/win32/thread.prf \
		../../../../Qt/4.8.6/mkspecs/features/moc.prf \
		../../../../Qt/4.8.6/mkspecs/features/win32/windows.prf \
		../../../../Qt/4.8.6/mkspecs/features/resources.prf \
		../../../../Qt/4.8.6/mkspecs/features/uic.prf \
		../../../../Qt/4.8.6/mkspecs/features/yacc.prf \
		../../../../Qt/4.8.6/mkspecs/features/lex.prf \
		../../../../Qt/4.8.6/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ..\..\..\..\Qt\4.8.6\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile notifier.pro
..\..\..\..\Qt\4.8.6\mkspecs\features\device_config.prf:
..\..\..\..\Qt\4.8.6\mkspecs\qconfig.pri:
..\..\..\..\Qt\4.8.6\mkspecs\modules\qt_webkit_version.pri:
..\..\..\..\Qt\4.8.6\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\win32\default_pre.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\debug.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\debug_and_release.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\default_post.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\win32\default_post.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\declarative_debug.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\win32\rtti.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\win32\exceptions.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\win32\stl.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\shared.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\qt.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\win32\thread.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\moc.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\win32\windows.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\resources.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\uic.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\yacc.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\lex.prf:
..\..\..\..\Qt\4.8.6\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\..\..\Qt\4.8.6\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile notifier.pro

qmake_all: sub-notifier-qmake_all sub-daemon-qmake_all FORCE

make_default: sub-notifier-make_default sub-daemon-make_default FORCE
make_first: sub-notifier-make_first sub-daemon-make_first FORCE
all: sub-notifier-all sub-daemon-all FORCE
clean: sub-notifier-clean sub-daemon-clean FORCE
distclean: sub-notifier-distclean sub-daemon-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-notifier-install_subtargets sub-daemon-install_subtargets FORCE
uninstall_subtargets: sub-notifier-uninstall_subtargets sub-daemon-uninstall_subtargets FORCE

sub-notifier-sub_Debug: notifier\$(MAKEFILE)
	cd notifier\ && $(MAKE) -f $(MAKEFILE) debug
sub-daemon-sub_Debug: daemon\$(MAKEFILE)
	cd daemon\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-notifier-sub_Debug sub-daemon-sub_Debug

sub-notifier-sub_Release: notifier\$(MAKEFILE)
	cd notifier\ && $(MAKE) -f $(MAKEFILE) release
sub-daemon-sub_Release: daemon\$(MAKEFILE)
	cd daemon\ && $(MAKE) -f $(MAKEFILE) release
release: sub-notifier-sub_Release sub-daemon-sub_Release

sub-notifier-check: notifier\$(MAKEFILE)
	cd notifier\ && $(MAKE) -f $(MAKEFILE) check
sub-daemon-check: daemon\$(MAKEFILE)
	cd daemon\ && $(MAKE) -f $(MAKEFILE) check
check: sub-notifier-check sub-daemon-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

